'use strict';

var gulp = require('gulp');

gulp.paths = {
  scripts: [
    'app/**/*.js',
    'config/*.js',
    'public/js/**/*.js'
  ],
};

/**
 * separating gulp tasks concerns inside the gulp dir
 * NOTE: tasks in this directory have been adapted from
 * tasks generated by github.com/kosz/generator-modular
 */
require('require-dir')('./gulp');
